-- DB とテーブル作成
CREATE DATABASE IF NOT EXISTS contactsdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE contactsdb;

CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  postal_code VARCHAR(10) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
